services:
  hugo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1313:1313"
    volumes:
      - .:/src
    command:
      - hugo
      - server
      - --bind
      - 0.0.0.0
      - --baseURL
      - http://127.0.0.1:1313
      - --buildDrafts
      - --disableFastRender
